graph TD
	A[mbtiles] --> B{Is your coverage area large?}
  B -->|No|C[narwassco/vt-map]
	B -->|Yes|D[wasac/vt]
  C -->|produce tiles locally|E[gh-pages]
  D -->|upload mbtiles|F[github master branch]
  F -->|produce tiles by Github Actions|E